defaults: &defaults
  adapter: postgis
  encoding: unicode
  template: template0

development:
  <<: *defaults
  url: "postgresql://postgres@localhost:5434/isolationgames_development"
  pool: 5

test:
  <<: *defaults
  url: "postgresql://postgres@localhost:5434/isolationgames_test"
  pool: 5

auroradefaults: &auroradefaults
  <<: *defaults
  sslmode: verify-ca

production:
  <<: *auroradefaults
  url: <%= ENV["PRIMARY_URL"] %>
  pool: 105
