#!/usr/bin/env ruby
require 'pathname'
require 'fileutils'

gem_name = ARGV.shift
gem_location = `bundle show #{gem_name}`.chomp
unless $?.success?
  puts "Error finding gem #{gem_name}..."
  abort gem_location
end

VENDOR_GEMS = Pathname.pwd.join("vendor", "gems")
destination = VENDOR_GEMS.join(gem_name)

if destination.exist?
  if ARGV.last != "--force"
    abort "#{gem_name} is already vendored - use --force to remove it so you can revendor from whatever is the version in your bundle"
  else
    FileUtils.rm_rf(destination)
  end
end

gem_path = Pathname(gem_location).expand_path
gem_name_with_version = gem_path.basename
gemspec_path = Pathname("#{gem_path}/../../specifications/#{gem_name_with_version}.gemspec").expand_path

puts "Vendoring #{gem_name} which is actually #{gem_name_with_version} to #{destination}"

FileUtils.cp_r(gem_path, destination)
FileUtils.cp(gemspec_path, destination)

puts %{Success - you can now change Gemfile to point at:}
puts
puts %{  gem "#{gem_name}", path: "vendor/gems/#{gem_name}"}
