name: Run Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.7
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports: ["5434:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: actions/setup-ruby@v1

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - name: Cache Gems
        id: gem-cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Cache NodeJS Modules
        id: node-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Bundle Install
        run: bundle install --path vendor/bundle --jobs 4 --retry 3

      - name: Yarn Install
        run: yarn install

      - name: Setup DB
        run: bin/rails db:drop db:create db:schema:load --trace

      - name: Add seed data
        run: bundle exec rake db:seed

      - name: Run RSpec
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          CI: "true"
        run: |
          bundle exec rspec --format RspecJunitFormatter \
            --format progress \
            --color
